# ===================================================================
# 项目主配置文件
# ===================================================================

# -------------------------------------------------------------------
# GAN 配置 (用于加载已训练好的模型)
# -------------------------------------------------------------------
gan:
  paths:
    # 最终选定的、训练好的生成器模型权重路径
    checkpoint_dir: "checkpoints/sc_gan/"

# -------------------------------------------------------------------
# Meta-Learning 配置 (客户端选择相关)
# (这部分参数暂时用于基线策略，未来将主要用于元学习模型)
# -------------------------------------------------------------------
meta:
  client_num: 1000        # 模拟的客户端总数
  max_clients: 10        # 每轮选择参与训练的客户端数量
  max_rounds: 100         # 联邦学习模拟的总轮次
  base_epochs: 2         # 每个客户端在本地训练的轮次 (Epochs)

# -------------------------------------------------------------------
# Federated Learning (FL) 配置
# (定义联邦学习任务和环境的参数)
# -------------------------------------------------------------------
fl:
  dataset: "mnist"  # 【修改】在这里选择数据集: "cifar10" 或 "mnist"
  model_type: "simple_cnn"
  num_classes: 10
  test_batch_size: 128

  # 【新增】聚合策略配置
  aggregation_strategy: "WeightedFedAvg"  # 可选项: "FedAvg", "WeightedFedAvg"

  # 数据异构性控制
  non_iid_alpha: 0.1

  # 模拟参数
  model_size: 10.0
